certmanager:
  enabled: false
installCertmanager: false

certmanager-issuer:
  email: cat@cat.com

gitlab-runner:
  install: false

prometheus:
  install: false

nginx-ingress:
  enabled: true
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443

global:
  hosts:
    domain: localhost
    https: false

  ingress:
    configureCertmanager: false
    tls:
      enabled: false
