apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/047cburgess/iot-public.git
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
