# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.provision "shell", inline: "apt-get update"
  #config.vm.provision "shell", path: "scripts/install-docker.sh"
  #config.vm.provision "shell", path: "scripts/guest-additions.sh"
  config.vm.provision "shell", path: "scripts/install-vagrant.sh"
end
