# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-13"

  # SERVER
  config.vm.define "caburgesS" do |server|
    server.vm.hostname = "caburgesS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.network :forwarded_port, guest: 80, host: 8888
    server.vm.provider "virtualbox" do |v|
      v.name = "caburgesS"
      v.memory = 1024
      v.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/install-k3s.sh"

    server.vm.synced_folder "./confs", "/confs"
    server.vm.provision "shell", inline: "kubectl apply -f /confs/"
  end

  config.trigger.after :up do |trigger|
    trigger.info = "Showing k3s configuration..."
    trigger.run = { inline: "vagrant ssh caburgesS -c 'kubectl get all'"}
  end

  config.trigger.after :up do |trigger|
    trigger.run = { inline: "echo -e '#{ENV['WELCOME_P2']}'" }
  end

end
