# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-13"

  # SERVER
  config.vm.define "caburgesS" do |server|
    server.vm.hostname = "caburgesS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.network :forwarded_port, guest: 80, host: 8888
    server.vm.provider "virtualbox" do |v|
      v.name = "caburgesS"
      v.memory = 1024
      v.cpus = 2
    end
    server.vm.provision "Install k3s", type: "shell", path: "scripts/install-k3s.sh"

    server.vm.synced_folder "./confs", "/confs"
    server.vm.provision "Apply k3s configuration", type: "shell", inline: "
      kubectl apply -f /confs/
      kubectl wait --for=condition=available deployment.apps/app-two
    "

    # Show k3s nodes and welcome message
    server.trigger.after [:up] do |trigger|
      trigger.ruby do |env, machine|
        system("bash scripts/after.sh")
      end
    end
  end

end
