# -*- mode: ruby -*-
# vi: set ft=ruby :
#

# Do not create symlinks inside shared folders
VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian12"

  # SERVER
  config.vm.define "caburgesS" do |server|
    server.vm.hostname = "caburgesS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "caburgesS"]
      v.memory = 1024
      v.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/install-k3s.sh"

    server.vm.synced_folder "/home/vagrant/iot/p2/confs", "/confs"
    server.vm.provision "shell", inline: "kubectl apply -f /confs/"
  end

#   # SERVER WORKER
#   config.vm.define "caburgesSW" do |worker|
#     worker.vm.hostname = "caburgesSW"
#     worker.vm.network "private_network", ip: "192.168.56.111"
#     worker.vm.provider "virtualbox" do |v|
#       v.customize ["modifyvm", :id, "--name", "caburgesSW"]
#       v.memory = 1024
#       v.cpus = 2
#     end
#     worker.vm.provision "shell", path: "scripts/install-k3s-worker.sh"
#     worker.vm.synced_folder "/home/vagrant/shared", "/token", create: true
#   end

  config.trigger.after :up do |trigger|
    trigger.info = "Showing k3s nodes..."
    trigger.run = { inline: "vagrant ssh caburgesS -c 'kubectl get nodes -o wide'"}
  end

end
