# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"


  # SERVER
  config.vm.define "caburgesS" do |control|
    control.vm.hostname = "caburgesS"
    control.vm.network "private_network", ip: "192.168.56.110"
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "caburgesS"]
      v.memory = 1024
      v.cpus = 1
    end
    config.vm.provision "shell", path: "scripts/install-k3s.sh"
  end

  #TODO set provider virtualbox, use minimumus from subject, and set virtualization 
  #TODO install k3s
end

#TODO 2nd vm
