# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  #TODO set provider virtualbox, use minimumus from subject, and set virtualization 
  #TODO install k3s
  config.vm.provision "shell", path: "scripts/install-k3s.sh"
end

#TODO 2nd vm
